=== api-evangelist/amazon-compute-optimizer/json-schema/compute-optimizer-auto-scaling-group-recommendation-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-compute-optimizer/refs/heads/main/json-schema/compute-optimizer-auto-scaling-group-recommendation-schema.json",
  "title": "AutoScalingGroupRecommendation",
  "description": "Describes an Auto Scaling group recommendation.",
  "type": "object",
  "properties": {
    "accountId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AccountId"
        },
        {
          "description": "The Amazon Web Services account ID of the Auto Scaling group."
        }
      ]
    },
    "autoScalingGroupArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AutoScalingGroupArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the Auto Scaling group."
        }
      ]
    },
    "autoScalingGroupName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AutoScalingGroupName"
        },
        {
          "description": "The name of the Auto Scaling group."
        }
      ]
    },
    "finding": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Finding"
        },
        {
          "description": "<p>The finding classification of the Auto Scaling group.</p> <p>Findings for Auto Scaling groups include:</p> <ul> <li> <p> <b> <code>NotOptimized</code> </b>\u2014An Auto Scaling group is considered not optimized when Compute Optimizer identifies a recommendation that can provide better performance for your workload.</p> </li> <li> <p> <b> <code>Optimized</code> </b>\u2014An Auto Scaling group is considered optimized when Compute Optimizer determines that the group is correctly provisioned to run your workload based on the chosen instance type. For optimized resources, Compute Optimizer might recommend a new generation instance type.</p> </li> </ul>"
        }
      ]
    },
    "utilizationMetrics": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UtilizationMetrics"
        },
        {
          "description": "An array of objects that describe the utilization metrics of the Auto Scaling group."
        }
      ]
    },
    "lookBackPeriodInDays": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LookBackPeriodInDays"
        },
        {
          "description": "The number of days for which utilization metrics were analyzed for the Auto Scaling group."
        }
      ]
    },
    "currentConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AutoScalingGroupConfiguration"
        },
        {
          "description": "An array of objects that describe the current configuration of the Auto Scaling group."
        }
      ]
    },
    "recommendationOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AutoScalingGroupRecommendationOptions"
        },
        {
          "description": "An array of objects that describe the recommendation options for the Auto Scaling group."
        }
      ]
    },
    "lastRefreshTimestamp": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LastRefreshTimestamp"
        },
        {
          "description": "The timestamp of when the Auto Scaling group recommendation was last generated."
        }
      ]
    },
    "currentPerformanceRisk": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CurrentPerformanceRisk"
        },
        {
          "description": "The risk of the current Auto Scaling group not meeting the performance needs of its workloads. The higher the risk, the more likely the current Auto Scaling group configuration has insufficient capacity and cannot meet workload requirements."
        }
      ]
    },
    "effectiveRecommendationPreferences": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EffectiveRecommendationPreferences"
        },
        {
          "description": "An object that describes the effective recommendation preferences for the Auto Scaling group."
        }
      ]
    },
    "inferredWorkloadTypes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/InferredWorkloadTypes"
        },
        {
          "description": "<p>The applications that might be running on the instances in the Auto Scaling group as inferred by Compute Optimizer.</p> <p>Compute Optimizer can infer if one of the following applications might be running on the instances:</p> <ul> <li> <p> <code>AmazonEmr</code> - Infers that Amazon EMR might be running on the instances.</p> </li> <li> <p> <code>ApacheCassandra</code> - Infers that Apache Cassandra might be running on the instances.</p> </li> <li> <p> <code>ApacheHadoop</code> - Infers that Apache Hadoop might be running on the instances.</p> </li> <li> <p> <code>Memcached</code> - Infers that Memcached might be running on the instances.</p> </li> <li> <p> <code>NGINX</code> - Infers that NGINX might be running on the instances.</p> </li> <li> <p> <code>PostgreSql</code> - Infers that PostgreSQL might be running on the instances.</p> </li> <li> <p> <code>Redis</code> - Infers that Redis might be running on the instances.</p> </li> <li> <p> <code>Kafka</code> - Infers that Kafka might be running on the instance.</p> </li> <li> <p> <code>SQLServer</code> - Infers that SQLServer might be running on the instance.</p> </li> </ul>"
        }
      ]
    }
  }
}

=== api-evangelist/amazon-compute-optimizer/examples/compute-optimizer-auto-scaling-group-recommendation-example.json
{
  "accountId": "example-string",
  "autoScalingGroupArn": "arn:aws:ec2:us-east-1:123456789012:instance/i-1234567890abcdef0",
  "autoScalingGroupName": "example-name",
  "finding": "example-string",
  "utilizationMetrics": "example-string",
  "lookBackPeriodInDays": "example-string",
  "currentConfiguration": "example-string",
  "recommendationOptions": "example-string",
  "lastRefreshTimestamp": "example-string",
  "currentPerformanceRisk": "example-string",
  "effectiveRecommendationPreferences": "example-string",
  "inferredWorkloadTypes": "ec2"
}
